language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install:
  - pip3 install pylint pep8 aiohttp

before_script:
  - pylint --version

script: 
  - pylint remotsylib/*.py
  - pylint examples/*.py
  - python setup.py bdist


notifications:
  email:
    on_success: never
    on_failure: change
